# Generated by Django 5.1.7 on 2025-04-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='user',
        ),
    ]
