# Generated by Django 5.1.7 on 2025-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='name',
        ),
        migrations.RemoveField(
            model_name='name',
            name='user',
        ),
        migrations.AddField(
            model_name='name',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
