# Generated by Django 5.1.7 on 2025-04-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='password',
        ),
        migrations.RemoveField(
            model_name='name',
            name='username',
        ),
    ]
