# Generated by Django 5.1.7 on 2025-04-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
