# Generated by Django 5.1.7 on 2025-04-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_name_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='todo',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.name'),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='api.userprofile')),
            ],
        ),
    ]
